### ISSUE TITLE
`Could not agree on API version for KlifeProtocol.Messages.Produce api_key 0 for client ...` when talking to Azure Event Hubs Kafka endpoint.

### ISSUE THREAD

**Issue by chgeuer** [oliveigah/klife#13]
I tried to establish a connection to the Kafka protocol head of an Azure Event Hubs endpoint. The sample seems to be able to establish the TLS connection, but then it can't "agree on API version":

```text
* (Mix) Could not start application example: Example.Application.start(:normal, []) returned an error: shutdown: failed to start child: Example.MySimplestClient
    ** (EXIT) shutdown: failed to start child: {Klife.Connection.Supervisor, Example.MySimplestClient}
        ** (EXIT) shutdown: failed to start child: Klife.Connection.Controller
            ** (EXIT) an exception was raised:
                ** (RuntimeError) Could not agree on API version for KlifeProtocol.Messages.Produce api_key 0 for client Elixir.Example.MySimplestClient. 
                    (klife 0.3.0) lib/klife/connection/message_versions.ex:46: Klife.Connection.MessageVersions.do_setup_versions/3
                    (klife 0.3.0) lib/klife/connection/controller.ex:146: Klife.Connection.Controller.handle_info/2
                    (klife 0.3.0) lib/klife/connection/controller.ex:127: Klife.Connection.Controller.do_init/1
                    (klife 0.3.0) lib/klife/connection/controller.ex:122: Klife.Connection.Controller.init/1
                    (stdlib 6.1.2) gen_server.erl:2229: :gen_server.init_it/2
                    (stdlib 6.1.2) gen_server.erl:2184: :gen_server.init_it/6
                    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

My configuration (`config/config.exs`) looks like this:

```elixir
import Config

config :example, Example.MySimplestClient,
  connection: [
    bootstrap_servers: ["samplechgeuer2.servicebus.windows.net:9093"],
    ssl: true,
    connect_opts: [
      verify: :verify_peer,
      cacerts: [
        # https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
        # self-signed "DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US"
        "MIIDjjCCAnagAwIBAgIQAzrx5qcRqaC7KGSxHQn65TANBgkqhkiG9w0BAQsFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBHMjAeFw0xMzA4MDExMjAwMDBaFw0zODAxMTUxMjAwMDBaMGExCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xIDAeBgNVBAMTF0RpZ2lDZXJ0IEdsb2JhbCBSb290IEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzfNNNx7a8myaJCtSnX/RrohCgiN9RlUyfuI2/Ou8jqJkTx65qsGGmvPrC3oXgkkRLpimn7Wo6h+4FR1IAWsULecYxpsMNzaHxmx1x7e/dfgy5SDN67sH0NO3Xss0r0upS/kqbitOtSZpLYl6ZtrAGCSYP9PIUkY92eQq2EGnI/yuum06ZIya7XzV+hdG82MHauVBJVJ8zUtluNJbd134/tJS7SsVQepj5WztCO7TG1F8PapspUwtP1MVYwnSlcUfIKdzXOS0xZKBgyMUNGPHgm+F6HmIcr9g+UQvIOlCsRnKPZzFBQ9RnbDhxSJITRNrw9FDKZJobq7nMWxM4MphQIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAdBgNVHQ4EFgQUTiJUIBiV5uNu5g/6+rkS7QYXjzkwDQYJKoZIhvcNAQELBQADggEBAGBnKJRvDkhj6zHd6mcY1Yl9PMWLSn/pvtsrF9+wX3N3KjITOYFnQoQj8kVnNeyIv/iPsGEMNKSuIEyExtv4NeF22d+mQrvHRAiGfzZ0JFrabA0UWTW98kndth/Jsw1HKj2ZL7tcu7XUIOGZX1NGFdtom/DzMNU+MeKNhJ7jitralj41E6Vf8PlwUHBHQRFXGU7Aj64GxJUTFy8bJZ918rGOmaFvE7FBcf6IKshPECBV1/MUReXgRPTqh5Uykw7+U0b6LJ3/iyK5S9kJRaTepLiaWN0bfVKfjllDiIGknibVb63dDcY3fe0Dkhvld1927jyNxF1WW6LZZm6zNTflMrY=",
        # "DigiCert Global Root G2, OU=www.digicert.com, O=DigiCert Inc, C=US" issuing "Microsoft Azure RSA TLS Issuing CA 03, O=Microsoft Corporation, C=US"
        # https://www.microsoft.com/pkiops/docs/repository.htm
        # https://www.microsoft.com/pkiops/certs/microsoft%20azure%20rsa%20tls%20issuing%20ca%2003%20-%20xsign.crt
        "MIIFrDCCBJSgAwIBAgIQBRllJkSaXj0aOHSPXc/rzDANBgkqhkiG9w0BAQwFADBhMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3d3cuZGlnaWNlcnQuY29tMSAwHgYDVQQDExdEaWdpQ2VydCBHbG9iYWwgUm9vdCBHMjAeFw0yMzA2MDgwMDAwMDBaFw0yNjA4MjUyMzU5NTlaMF0xCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLjAsBgNVBAMTJU1pY3Jvc29mdCBBenVyZSBSU0EgVExTIElzc3VpbmcgQ0EgMDMwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCUaitvevlZirydcTjMIt2fr5ei7LvQx7bdIVobgEZ1Qlqf3BH6etKdmZChydkN0XXAb8Ysew8aCixKtrVeDCe5xRRCnKaFcEvqg2cSfbpXFevXDvfbTK2ed7YASOJ/pv31stqHd9m0xWZLCmsXZ8x6yIxgEGVHjIAOCyTAgcQy8ItIjmxn3Vu2FFVBemtP38Nzur/8id85uY7QPspI8Er8qVBBBHp6PhxTIKxAZpZbXtBf2VxIKbvUGEvCxWCrKNfv+j0oEqDpXOqGFpVBK28Q48u/0F+YBUY8FKP4rfgFI4lG9mnzMmCL76k+HjyBtU5zikDGqgm4mlPXgSRqEh0CvQS7zyrBRWiJCfK0g67f69CVGa7fji8pz99J59s8bYW7jgyro93LCGb4N3QfJLurB//ehDp33XdIhizJtopjUoFUGLnomVnMRTUNtMSAy7J4r1yjJDLufgnrPZ0yjYo6nyMiFswCaMmFfclUKtGzzbPDpIBuf0hmvJAt0LyWlYUst5geusPxbkM5XOhLn7px+/y+R0wMT3zNZYQxlsLDbXGYsRdE9jxcIts+IQwWZGnmHhhC1kvKC/nAYcqBZctMQB5q/qsPH652dc73zOx6Bp2gTZqokGCv5PGxiXcrwouOUIlYgizBDYGBDU02S4BRDM3oW9motVUonBnF8JHVRwIDAQABo4IBYjCCAV4wEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU/glxQFUFEETYpIF1uJ4a6UoGiMgwHwYDVR0jBBgwFoAUTiJUIBiV5uNu5g/6+rkS7QYXjzkwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB2BggrBgEFBQcBAQRqMGgwJAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBABggrBgEFBQcwAoY0aHR0cDovL2NhY2VydHMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsUm9vdEcyLmNydDBCBgNVHR8EOzA5MDegNaAzhjFodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxSb290RzIuY3JsMB0GA1UdIAQWMBQwCAYGZ4EMAQIBMAgGBmeBDAECAjANBgkqhkiG9w0BAQwFAAOCAQEAAQkxu6RRPlD3yrYhxg9jIlVZKjAnC9H+D0SSq4j1I8dNImZ4QjexTEv+224CSvy4zfp9gmeRfC8rnrr4FN4UFppYIgqR4H7jIUVMG9ECUcQj2Ef11RXqKOg5LK3fkoFz/Nb9CYvg4Ws9zv8xmE1Mr2N6WDgLuTBIwul2/7oakjj8MA5EeijIjHgB1/0r5mPmeFYVx8xCuX/j7+q4tH4PiHzzBcfqb3k0iR4DlhiZfDmy4FuNWXGM8ZoMM43EnRN/meqAcMkABZhY4gqeWZbOgxber297PnGOCcIplOwpPfLu1A1K9frVwDzAG096a8L0+ItQCmz7TjRH4ptX5Zh9pw=="
      ] |> Enum.map(&Base.decode64!/1),
      server_name_indication: String.to_charlist("servicebus.windows.net"),
      depth: 3
      # cacertfile: Path.relative("test/compose_files/ssl/ca.crt")
    ],
    socket_opts: [delay_send: true],
    sasl_opts: [
      mechanism: "PLAIN",
      mechanism_opts: [
        username: "$ConnectionString",
        password: "Endpoint=sb://samplechgeuer2.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<redacted>"
      ]
    ],
  ],
  topics: [
    [
      name: "hub1",
      default_partitioner: Example.MyPartitioner
    ]
  ]
```

I slapped in an Inspect statement into `lib/klife/connection/message_versions.ex#do_setup_versions/3`:

```elixir
  # TODO: Handle non required messages
  defp do_setup_versions([{mod, client_data} | rest] = client_versions, server_map, client_name) do
    IO.inspect(
      %{
        client_versions: client_versions,
        server_map: server_map,
        client_name: client_name,
        api_key: mod.api_key(),
        mod: mod
      },
      label: "do_setup_versions"
    )
```

which outputs

```elixir
do_setup_versions: %{
  mod: KlifeProtocol.Messages.ApiVersions,
  api_key: 18,
  client_name: Example.MySimplestClient,
  client_versions: [
    {KlifeProtocol.Messages.ApiVersions,        %{min: 0, max: 0}},
    {KlifeProtocol.Messages.CreateTopics,       %{min: 0, max: 0}},
    {KlifeProtocol.Messages.Metadata,           %{min: 1, max: 1}},
    {KlifeProtocol.Messages.Produce,            %{min: 9, max: 9}},
    {KlifeProtocol.Messages.InitProducerId,     %{min: 0, max: 0}},
    {KlifeProtocol.Messages.Fetch,              %{min: 4, max: 4}},
    {KlifeProtocol.Messages.ListOffsets,        %{min: 2, max: 2}},
    {KlifeProtocol.Messages.AddPartitionsToTxn, %{min: 4, max: 4}},
    {KlifeProtocol.Messages.FindCoordinator,    %{min: 4, max: 4}},
    {KlifeProtocol.Messages.EndTxn,             %{min: 3, max: 3}},
    {KlifeProtocol.Messages.SaslHandshake,      %{min: 1, max: 1}},
    {KlifeProtocol.Messages.SaslAuthenticate,   %{min: 1, max: 1}}
  ],
  server_map: %{
     0 => %{min: 0, max: 7},
     1 => %{min: 4, max: 6},
     2 => %{min: 0, max: 8},
     3 => %{min: 0, max: 5},
     8 => %{min: 0, max: 8},
     9 => %{min: 0, max: 8},
    10 => %{min: 0, max: 4},
    11 => %{min: 0, max: 9},
    12 => %{min: 0, max: 4},
    13 => %{min: 0, max: 5},
    14 => %{min: 0, max: 5},
    15 => %{min: 0, max: 5},
    16 => %{min: 0, max: 4},
    17 => %{min: 0, max: 1},
    18 => %{min: 0, max: 3},
    19 => %{min: 0, max: 6},
    20 => %{min: 0, max: 2},
    21 => %{min: 0, max: 2},
    22 => %{min: 0, max: 4},
    23 => %{min: 0, max: 0},
    32 => %{min: 0, max: 2},
    36 => %{min: 0, max: 2},
    37 => %{min: 0, max: 1},
    42 => %{min: 0, max: 2},
    47 => %{min: 0, max: 0}
  }
}
```

which (as mentiond earlier) results in ` Could not agree on API version for KlifeProtocol.Messages.Produce api_key 0 for client Elixir.Example.MySimplestClient.`. 

I'm not totally in the whole Kafka protocol negotiation aspect here... 

## local repro

Using this code, you see the same error:

```elixir
Mix.install([
  {:klife, "~> 0.3.0"}
])

Klife.Connection.MessageVersions.setup_versions(%{
     0 => %{min: 0, max: 7},  1 => %{min: 4, max: 6},  2 => %{min: 0, max: 8},
     3 => %{min: 0, max: 5},  8 => %{min: 0, max: 8},  9 => %{min: 0, max: 8},
    10 => %{min: 0, max: 4}, 11 => %{min: 0, max: 9}, 12 => %{min: 0, max: 4},
    13 => %{min: 0, max: 5}, 14 => %{min: 0, max: 5}, 15 => %{min: 0, max: 5},
    16 => %{min: 0, max: 4}, 17 => %{min: 0, max: 1}, 18 => %{min: 0, max: 3},
    19 => %{min: 0, max: 6}, 20 => %{min: 0, max: 2}, 21 => %{min: 0, max: 2},
    22 => %{min: 0, max: 4}, 23 => %{min: 0, max: 0}, 32 => %{min: 0, max: 2},
    36 => %{min: 0, max: 2}, 37 => %{min: 0, max: 1}, 42 => %{min: 0, max: 2},
    47 => %{min: 0, max: 0} }, "client_name")

# Could not agree on API version for KlifeProtocol.Messages.Produce api_key 0 for client client_name. 
```

**Comment by oliveigah** [comment]
Hey @chgeuer! Thanks for the report.

The problem seems like your server supports only up to produce version 7.

```elixir
# server map
0 => %{min: 0, max: 7},
```

Klife minimun requirement now is 9. But I can change it so you can give it a try! 

```elixir
# klife 
{KlifeProtocol.Messages.Produce, %{min: 9, max: 9}},
```

Gonna take a look on the changes needed to support produce 7 and I'll report back here. Should not take long, today after work I can take a look at this and release a new version for you.

**Comment by chgeuer** [comment]
Got it, yeah, that might be good. Now I finally understood that these numbers correspond to the API Keys from [kafka protocol](https://kafka.apache.org/protocol.html#protocol_api_keys)...

**Comment by oliveigah** [comment]
@chgeuer I've just released the new version 0.4.0

It has 2 changes that impacts you:
- Producer (api_key 0) now supports versions 3 to 9
- AddPartitionsToTxn (api_key 24) now do not raise, but warnings and transactions won't work

I've done the AddPartitionsToTxn change because by your logs your server also does not seems to return api_key 24, so you would still had problems without it. But be aware that if your server does not return it you won't be able to use transactions.

Let me know if the new version solves it for you! (:

**Comment by chgeuer** [comment]
Thanks @oliveigah, 

following your path, I also disabled raising for the `{M.EndTxn, %{min: 3, max: 3, raise?: false}},` thing, so it now logs

```text
16:12:53.206 [warning] Transactions will not work because could not agree on API version for KlifeProtocol.Messages.AddPartitionsToTxn api_key 24 for client Elixir.Example.MySimplestClient.

16:12:53.212 [warning] Some features may not work because could not agree on API version for KlifeProtocol.Messages.EndTxn api_key 26 for client Elixir.Example.MySimplestClient
```

However now I'm getting another crash

```text
16:13:24.168 [notice] Application example exited: Example.Application.start(:normal, []) returned an error: shutdown: failed to start child: Example.MySimplestClient
    ** (EXIT) shutdown: failed to start child: Klife.Producer.Supervisor
        ** (EXIT) shutdown: failed to start child: Klife.Producer.Controller
            ** (EXIT) an exception was raised:
                ** (CaseClauseError) no case clause matching: {:error, {%RuntimeError{message: "timeout while waiting for broker response"}, [{Klife.Producer, :do_with_timeout, 2, [file: ~c"lib/klife/producer/producer.ex", line: 595, error_info: %{module: Exception}]}, {Klife.Producer, :set_producer_id, 1, [file: ~c"lib/klife/producer/producer.ex", line: 348]}, {Klife.Producer, :init, 1, [file: ~c"lib/klife/producer/producer.ex", line: 258]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 2229]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 2184]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 329]}]}}
                    (klife 0.4.0) lib/klife/producer/controller.ex:258: anonymous fn/4 in Klife.Producer.Controller.handle_txn_producers/1
                    (elixir 1.17.3) lib/enum.ex:4415: Enum.reduce/3
                    (elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
                    (klife 0.4.0) lib/klife/producer/controller.ex:226: Klife.Producer.Controller.handle_txn_producers/1
                    (klife 0.4.0) lib/klife/producer/controller.ex:97: Klife.Producer.Controller.handle_info/2
                    (klife 0.4.0) lib/klife/producer/controller.ex:67: Klife.Producer.Controller.do_init/1
                    (klife 0.4.0) lib/klife/producer/controller.ex:63: Klife.Producer.Controller.init/1
                    (stdlib 6.1.2) gen_server.erl:2229: :gen_server.init_it/2
```

Will take some time to try understand what's going on.

**Comment by oliveigah** [comment]
@chgeuer, it looks like a problem on the FindCoordinator message when we pass a transactional_id not nil. 

I would suggest a couple things:

1 - To see the root problem, check the error_code that is returned  here, https://github.com/oliveigah/klife/blob/18a41f513cf3902f5ee87a9c3cd11eb4af08caf5/lib/klife/producer/producer.ex#L388

2 - To "skip" the problem, you could do not start transactional producers by commenting it here: https://github.com/oliveigah/klife/blob/18a41f513cf3902f5ee87a9c3cd11eb4af08caf5/lib/klife/producer/controller.ex#L326 

I should probaly have a config option to disable transactional producers in scenarios like this. Gonna implement this weekend.

Gonna also check if we should handle some other error_code as sucess other than 0.

**Comment by oliveigah** [comment]
Hey @chgeuer, I've released a new version 0.5.0 that may help you! 

It includes the 2 features I've mentioned above.

- Dynamically disable features based on api version negotiation failures (this may solve your problem)
- Add some logs to the initProducerId and findCoordinator calls

Let me know if it is good now! (:

**Comment by oliveigah** [comment]
Can we close this issue @chgeuer? Did you have a chance to test it out?

I'm expecting that the normal produce API calls would work but the transactions won't.

**Comment by chgeuer** [comment]
Let's close it, I still need to spend more time on learning about your library. Thanks for you help, Christian

**Comment by oliveigah** [comment]
Let me know if you would like some clarification on anything you need about the library! 

Thanks @chgeuer!
