### ISSUE TITLE
Error when connecting with Confluent Kafka

### ISSUE THREAD

**Issue by mateoramos97** [oliveigah/klife#14]
Hello,

I'm tryin to connect with my confluent kafka cluster, not sure why but always get this error

`** (Mix) Could not start application producer_service: ProducerService.Application.start(:normal, []) returned an error: shutdown: failed to start child: ProducerService.KafkaClient
    ** (EXIT) shutdown: failed to start child: {Klife.Connection.Supervisor, ProducerService.KafkaClient}
        ** (EXIT) shutdown: failed to start child: Klife.Connection.Controller
            ** (EXIT) an exception was raised:
                ** (MatchError) no match of right hand side value: {:error, :closed}
                    (klife 0.5.0) lib/klife/connection/controller.ex:460: Klife.Connection.Controller.negotiate_api_versions/2
                    (klife 0.5.0) lib/klife/connection/controller.ex:145: Klife.Connection.Controller.handle_info/2
                    (klife 0.5.0) lib/klife/connection/controller.ex:129: Klife.Connection.Controller.do_init/1
                    (klife 0.5.0) lib/klife/connection/controller.ex:124: Klife.Connection.Controller.init/1
                    (stdlib 6.1.2) gen_server.erl:2229: :gen_server.init_it/2
                    (stdlib 6.1.2) gen_server.erl:2184: :gen_server.init_it/6
                    (stdlib 6.1.2) proc_lib.erl:329: :proc_lib.init_p_do_apply/3`

I have this setup in my config file

`config :producer_service, ProducerService.KafkaClient,
  connection: [
    bootstrap_servers: [
      "my-confluent-host.confluent.cloud:9092"
      ],
    ssl: false,
    sasl_opts: [
      mechanism: "PLAIN",
      mechanism_opts: [
        username: "username",
        password: "password"
      ]
    ]
  ],
  topics: [[name: "commission_engine_pxch"]]`

I also tried to change the ssl config to true, and tried a lot of variations but always get the same error, I hided host, username and password, not sure if someone is able to create a free confluent cluster and stablish a connection, I just need to be able to produce events, dont need a consumer

**Comment by oliveigah** [comment]
Hey @mateoramos97!  Thanks for the report.
 
First thing is I would suggest always have `ssl: true` when using sasl plain. Otherwise your secrets could be exposed. I think we don't allow sasl_plain with ssl false.

Regarding your connection problem, it is weird. On my local tests I use the confluent latest image.

Just to be sure it is not a server configuration problem, are you able to connect using other libraries such as brod or kafka_ex?

If you have access to the server logs you should probally see some error regarding this closed connection.

Gonna try create a free confluent cluster later to see if I can reproduce your problem, which version of kafka are you running? Can you describe how do you created your cluster on confluent?

**Comment by oliveigah** [comment]
@mateoramos97 ,

I've reproduced your error on a confluent cloud cluster only when using `ssl: false` but everything works with `ssl: true`. 

With ssl: false I get:

```
:erlang.monitor(:process, {:error, {:shutdown, {:failed_to_start_child, MyClient, {:shutdown, {:failed_to_start_child, {Klife.Connection.Supervisor, MyClient}, {:shutdown, {:failed_to_start_child, Klife.Connection.Controller, {{:badmatch, {:error, :closed}}, [{Klife.Connection.Controller, :negotiate_api_versions, 2, [file: ~c"lib/klife/connection/controller.ex", line: 460]}, {Klife.Connection.Controller, :handle_info, 2, [file: ~c"lib/klife/connection/controller.ex", line: 145]}, {Klife.Connection.Controller, :do_init, 1, [file: ~c"lib/klife/connection/controller.ex", line: 129]}, {Klife.Connection.Controller, :init, 1, [file: ~c"lib/klife/connection/controller.ex", line: 124]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 851]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 240]}]}}}}}}}})
```

With `ssl: true` I can successfully produce to the cluster:

![image](https://github.com/user-attachments/assets/1c1d266f-bf8d-4e8d-b6b1-bb77b103e568)

Can you give it a try with the following config:

```
config :producer_service, ProducerService.KafkaClient, connection: [ bootstrap_servers: [ "my-confluent-host.confluent.cloud:9092" ], ssl: true, sasl_opts: [ mechanism: "PLAIN", mechanism_opts: [ username: "username", password: "password" ] ] ], topics: [[name: "commission_engine_pxch"]]
```
